services:
  uvicorn-test:
    build: .
    ports:
      - "${APP_PORT}:8081"
    environment:
      - APP_ENV=${APP_ENV}
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /usr/local/app/src
        - action: rebuild
          path: requirements.txt
    volumes:
      - persistent-storage:/usr/local/app/persistent-storage

volumes:
  persistent-storage: